### ISSUE TITLE
Need to test automated/scheduled provision of client machines

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#19]

**Comment by shall1024** [comment]
Automated/scheduled provision of client machines is, more or less, in the same state as manual provisioning. Currently the following distros provision and report correctly:

- RHEL 7.9
- Fedora 32

The following distros provision correctly but do not have a valid test harness, therefore, results are not reported correctly (check-install appears to fail and users are never given email notification that the system is reserved):

- Fedora 31
- RHEL 8.1

The following distros fail immediately upon attempting to provision because a valid test harness cannot be found:

- Fedora 33

Fedora 31 does not seem to have a harness repo available on the Beaker site. Fedora 33 does, as does RHEL 8. Fedora 33 may see more success if the Beaker version on the server/lab controller is fully upgraded, but this still needs to be tested.

**Comment by shall1024** [comment]
I am in contact with the Beaker folks and we should have a Fedora 31 harness shortly.

I fully upgraded the lab controller, and the same Fedora 33 error persists. [This bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1874023) has an answer from Martin Styk that makes me a bit worried, but I recall that Fedora 33 testing has been done successfully with Beaker, plus there is indeed a Restraint harness for Fedora 33 located [here](https://beaker-project.org/yum/harness/Fedora33/), so I will see if I can get Beaker to use this.

**Comment by shall1024** [comment]
Fedora 33 now begins installation correctly. With the fix I found, I am confident RHEL 8.2 might work better as well.

I will test both of these when Doug is finished running the setup scripts on all 10 nodes.

**Comment by shall1024** [comment]
**Distros that provision correctly:**
Fedora32
Fedora33
RHEL 7.9

**Distros that do not provision correctly (Installation completes successfully, but harness issues prevent proper reporting):**
Fedora31 (Beaker sent us the harness, but need to get Beaker to use it. Low priority for now due to the fact that f31 is relatively older)
RHEL 8.2

**Untested:**
Fedora34

**Comment by shall1024** [comment]
Created a [PR](https://github.com/OpenFabrics/fsdp_beaker_snippets/pull/13) with the necessary changes for RHEL 8.0-8.4 to provision correctly.
