### ISSUE TITLE
Need to document the builder machine(s)

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#20]

**Comment by dledford** [comment]
Add a new builders.md page to describe the build machine(s), how they can be accessed, etc.

**Comment by lylavoie** [comment]
As part of this issue, let's setup HTTPD to server out public from people's home directories and document how they can use that or sshfs to access the contact from builder while working on a test node. That will give two different options to support access to the builder home directories.

Builder does already serve its home directories via NFS4, but permissions are controlled through Kerberos, so which complicates mounting the home directory from a test node, since it's not part of the IPA domain.

**Comment by lylavoie** [comment]
builder should be setup for the public_html directory for homes / users.  @lylavoie will create an update documentation for how this is setup in the builders.md file.
