### ISSUE TITLE
Create container builder environments

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#23]
This has been started, building on the CKI environments, however, these images can currently only be built from inside Redhat (i.e. points to internal repos).  We will need to either fork the CKI environment, or we will need to work with the CKI team to upstream changes that would allow the containers to built in the wide world.

@shall1024  was looking into this.

**Comment by lylavoie** [comment]
Will start with a target of getting OpenMPI to compile within the container, building containers for RHEL7, and RHEL8.

**Comment by lylavoie** [comment]
CKI containers will not work directly, because they point to internal repos that are available directly.  We'll need to reproduce the container environment, but pointing to public facing repos.

**Comment by shall1024** [comment]
Currently working on simple Dockerfiles for RHEL7 and RHEL8 container images, somewhat based on the CKI approach but using our own scripts/dockerfiles.

**Comment by shall1024** [comment]
Simple Dockerfiles have been created for RHEL 7 and 8 that have been used to build container images using `podman`.
These Dockerfiles can include any packages we want for these container images. Please let us know if there are lists of required packages for each distro.

It seems like, for our current purposes of getting some container images created so users can start using them, we do not need the CKI approach/scripts at this time.

**Comment by shall1024** [comment]
According to [this link](https://docs.fedoraproject.org/en-US/packaging-guidelines/MPI/), Fedora does not have `mvapich1` or `mvapich2`, only `mpich`. Please let me know if this is correct. For the first Dockerfiles, I am going to use `mpich` for all Fedora distros we support.

**Comment by dledford** [comment]
@shall1024 you are correct, Fedora doesn't have mvapich2, that's RHEL only.  Forgot about that.  I wouldn't both with mpich, it doesn't support RDMA.  The only reason I listed the programs I did is because once you satisfy their BuildRequires: elements, you will probably have all of the needed packages to have a usable build environment for everything else.  Because mpich doesn't use RDMA, whatever build requirements it *does* have are mostly moot to us.

Maybe for Fedora do: kernel, libfabric, opensm, openmpi, and ucx?  That should be a good mix and get all the dependecies resolved.

**Comment by shall1024** [comment]
Will we still need python3-pyverbs for Fedora? 

It seems like Fedora31 doesn't readily have python3-pyverbs, but maybe it's in another repository I need to add.

**Comment by dledford** [comment]
pyverbs is part of rdma-core, so as long as you have the most recent rdma-core for a given Fedora release, you'll have whatever pyverbs support that Fedora has.  Since pyverbs is relatively new, if they haven't updated the rdma-core on an older Fedora release, it won't have pyverbs.

**Comment by shall1024** [comment]
The first draft of the Dockerfiles can be found [here](https://github.com/OpenFabrics/fsdp_build/tree/main/dockerfiles); all it consists of is package lists, right now.

**Comment by JSpewock** [comment]
Edited Dockerfiles can be found [here](https://github.com/OpenFabrics/fsdp_build/tree/testing/dockerfiles). These are all functioning as of now but there were a few dependencies I changed around. Like, for example, fedora31 said it couldn't find python3-pyverbs and then in both rhel 7 and 8 dockerfiles I just have it doing a group install of Development tools rather than specific dependencies. Unsure if the dev tools have everything we need but if it doesn't it should be a quick fix.
