### ISSUE TITLE
Beaker mail items are dropping into a black hole currently

### ISSUE THREAD

**Issue by dledford** [OpenFabrics/fsdp_docs#24]
Beaker sends all sorts of notices that aren't currently going to be able to go through

**Comment by lylavoie** [comment]
IOL email server (postal.iol.unh.edu) should already allow relay from OFA FSDP lab IP address ranges, so beaker just needs to be configured to use this as its mail relay.

**Comment by lylavoie** [comment]
Also, need to make sure the "reply-to" address is something valid, so if a user replies, we see it.

**Comment by shall1024** [comment]
It turns out Beaker was not enabled to send email notifications at all, so that setting is now on. 
It now will send emails to ofalab@iol.unh.edu if someone reports a problem on a device, and it sends email notifications to a user when their jobs finish/if their jobs are cancelled/if their jobs are aborted. 

Are there other situations you would like us to test? Is the administrator supposed to receive emails whenever anyone reserves a system/users perform other actions? That is not something that is currently occurring.

**Comment by dledford** [comment]
Normally we get notifications to machine owner for loan requests and for whenever a machine goes offline in addition to the items you listed.  That would cover all the email alerts that we have enabled and that I know of.

----- Original Message -----
> It turns out Beaker was not enabled to send email notifications at all, so
> that setting is now on.
> It now will send emails to ofalab@iol.unh.edu if someone reports a problem on
> a device, and it sends email notifications to a user when their jobs
> finish/if their jobs are cancelled/if their jobs are aborted.
> 
> Are there other situations you would like us to test? Is the administrator
> supposed to receive emails whenever anyone reserves a system/users perform
> other actions? That is not something that is currently occurring.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenFabrics/fsdp_docs/issues/24#issuecomment-780817187

-- 
Doug Ledford <dledford@redhat.com>
              GPG KeyID: 0E572FDD
