### ISSUE TITLE
Auto-pull / update beaker snippet files on beaker

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#36]
Set up the beaker system to automatically update the beaker snippet files from a repo, so the system tracks the main branch of the repo.

**Comment by shall1024** [comment]
@dledford , based on my research on trying to clone a subdirectory via git instead of the entire git repository, along with the version of Git we have on the beaker server, I think it may be simplest and fastest to create a new Git repository for the Beaker snippets.

It should consist only of a folder named `snippets`, and the contents should be identical to the `beaker_snippets` directory from fsdp_setup.

Once this exists we should be able to quickly create a cron job that will allow us to auto-pull from the main branch.

**Comment by dledford** [comment]
New repository fsdp_beaker_snippets has been created and contains the directory snippets/ with all the data moved over from the other repo.

**Comment by shall1024** [comment]
There is a cron job on `beaker.ofa.iol.unh.edu` running every five minutes that auto-pulls the Beaker snippets from the main branch of `fsdp_beaker_snippets` and moves them to the correct folder so Beaker can use them.
