### ISSUE TITLE
RHEL 8 Snippet Changes cause Installation to Fail

### ISSUE THREAD

**Issue by shall1024** [OpenFabrics/fsdp_docs#58]
The new snippets are causing RHEL8 installs/provisions to fail.

I have identified the following two issues:

1. The EPEL repo is causing issues in the install. This is unexpected, because RHEL7 also has this repo in its `per_osmajor/system/RedHatEnterpriseLinux7` section and this does not cause issues.
2. Moving the `sed` command that sets `gpgcheck=1` for the repositories we've added to `system_post` causes the command to be executed too late. The `restraint_rhts` package is installed BEFORE `system_post` commands are reached.

Regarding point 2., I think the `%post` section needs to be put back in `per_osmajor/system/RedHatEnterpriseLinux8` based on what I read [here](https://access.redhat.com/solutions/1535203); otherwise, I don't see another way to run the `sed` command before `system_post`.

**Comment by dledford** [comment]
Regarding 1, is it just because of the gpgcheck, or something else about the epel repo causing problems?

Regarding 2, moving the snippet back will be fine.  All it really does is create two separate %post/%end segments in the kickstart, one that is out of place.  But, by being out of place, when Anaconda sanitizes the kickstart, it ends up appending the second, larger segment onto this very short out of place segment and that allows the sed command to preceed the rhts harness installs.  It's kind of an abuse of the Anaconda file format, but it works, so we can go back to it.  The other option would be to go into the beaker provided system_post template and put the sed command in there prior to the rhts package installs.

**Comment by shall1024** [comment]
Just attempted another provision with the `%post` section AND the epel repo, the epel repo causes the following error before installation can even begin:
```
      
Installation      
1) [x] Language settings                 2) [x] Time settings 
       (English (United States))                (America/New_York timezone) 
3) [!] Installation source               4) [!] Software selection 
       (Error setting up software               (Error checking software 
       source)                                  selection) 
5) [x] Installation Destination          6) [x] Kdump 
       (Automatic partitioning                  (Kdump is enabled) 
       selected) 
7) [x] Network configuration             8) [ ] User creation 
       (Wired (eno5) connected)                 (No user will be created)      
   
```

This causes the installation to hang at this point and never complete.

**Comment by shall1024** [comment]
Currently trying a fix, will report back if it works.

**Comment by shall1024** [comment]
RHEL8 installs have been fixed. RHEL7 still needs to be tested again, but it seemed like those snippets were fine last week.

Fedora34 still seems to be having issues; need to figure this out tomorrow morning.

I will create a PR with the fixed snippets as soon as I've confirmed all distros work again.

**Comment by shall1024** [comment]
PR has been created [here](https://github.com/OpenFabrics/fsdp_beaker_snippets/pull/21).

Once the PR is accepted I will close the issue and restart the cron job that automatically pulls Beaker snippets.

**Comment by dledford** [comment]
@shall1024 
Pull request merged
