### ISSUE TITLE
DHCP on fabric networks

### ISSUE THREAD

**Issue by lylavoie** [OpenFabrics/fsdp_docs#8]
I don't think we should run DHCP on the fabric networks, because there isn't a clean option / location to host that server.  I would prefer we didn't have to propagate those networks / vlans outside of the fabric switches, which will make them more flexible, because we don't have to avoid overlap with other operations / systems in the larger lab (outside of FSDP).

I've removed that from the network diagram for now.

Thoughts / comments?

**Comment by dledford** [comment]
It's *highly* desirable to have dhcp running on the various fabrics.  However, that dhcp need not be under beaker control (or even knowledge).  Because there have been specific bugs in the past that rendered IPoIB dhcp broken, not testing it leaves open a path for bugs that should be caught to be missed instead.

We already need one machine to act as a build server.  And we need at least one machine to be an OPA fabric manager.  We can use the switch SM for InfiniBand.  And Ethernet doesn't need a switch SM.  We can simply add dhcp to the list of services provided by whatever host does the OPA SM.  Right now, that's likely to be the build machine.  That keeps it from impacting the larger lab setup, and we want the build machine connected to all the fabrics if at all possible, so it should be OK.

**Comment by lylavoie** [comment]
As long as we're comfortable with the configurations / DHCP services running on the build server, that would be ok, and would keep those networks contained to the rack.  Otherwise, we have to align them with the lab.  The downside is, that is one more thing on the build server we have to keep an eye on (all-be-it a small one, since it's likely a fairly static config).  I'll add it back to the figure text.

**Comment by dledford** [comment]
Yeah, it won't be a big deal.  The rdma-setup scripts we have handle it automatically.  I have to make those scripts more user friendly before I upload them, and they'll end up being another git repo probably (they're a git repo internally already anyway).

If you put the dhcp back into the image, is it even any longer changed?  Or do we just drop the pull request?

**Comment by lylavoie** [comment]
I'll update the request, the other parts are changed to list our real IP addresses and VLANs.
